### PR TITLE
Add project_name to goreleaser configs

### PR DESCRIPTION
**Pull request by rquitales**
### Proposed changes

Unblocks goreleaser CI runs when GoReleaser v1.21 is used. This is a fix similar to https://github.com/pulumi/ci-mgmt/pull/618.

### Related issues (optional)
Example failed run: https://github.com/pulumi/pulumi-kubernetes/actions/runs/6347674862

### CODE REVIEW

**Comment by t0yv0** [comment]
Perhaps edit the notes in these files:

```
# WARNING: This file is autogenerated - changes will be overwritten if not made via https://github.com/pulumi/ci-mgmt
```

if we don't plan to currently manage this via ci-mgmt. Thank you!

**Review by t0yv0 — APPROVED** [review]

**Comment by rquitales** [comment]
> Perhaps edit the notes in these files:
> 
> ```
> # WARNING: This file is autogenerated - changes will be overwritten if not made via https://github.com/pulumi/ci-mgmt
> ```
> 
> if we don't plan to currently manage this via ci-mgmt. Thank you!

Good idea. Done!

**Comment by mjeffryes** [comment]
Actually, I think kubernetes is in sync with ci-mgmt now; I'd rather turn on the automation there and save ourselves from needing to keep track in different places.

**Comment by rquitales** [comment]
Holding on merge for now!

**Comment by rquitales** [comment]
Superseded by: https://github.com/pulumi/ci-mgmt/pull/636 and https://github.com/pulumi/pulumi-kubernetes/pull/2586.

**Pull request closed without merging**
