### PR TITLE
Fix helm example test by pinning pulumi package

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Comment by ellismg** [comment]
Does this mean when we release the next version of @pulumi/pulumi we will break this test?

**Comment by lblackstone** [comment]
@ellismg I'm not sure. The problem here was that it was using the `dev` package, which apparently broke/removed the `additionalSecretOutputs` option.

**Comment by ellismg** [comment]
> The problem here was that it was using the dev package, which apparently broke/removed the additionalSecretOutputs option.

That doesn’t sound good. The “dev” packages correspond to what is in master, so when we do a release, I would expect this problem to show back up since we will tag that release with “latest”.

Is there an issue about the break or a failing CI job I can look at? I don’t think this is the right long term fix.

**Comment by lblackstone** [comment]
@ellismg Yeah, the failing log is here: https://api.travis-ci.com/v3/job/208754658/log.txt
Search for `index.ts(63,54): error TS2339: Property 'clusterIP' does not exist on type 'Output<any>'.`

**Comment by ellismg** [comment]
Thanks, I’ll take a look later tonight.

**Comment by ellismg** [comment]
@CyrusNajmabadi, the test (when using a dev version) is failing to compile from TS with this error:

```
pulumi:pulumi:Stack (helm-chart-p-it-travis-job-helm-9310f60a):
  error: Running program '/tmp/p-it-travis-job-helm-9310f60a-973335404' failed with an unhandled exception:
  TSError: â¨¯ Unable to compile TypeScript:
  index.ts(34,5): error TS2322: Type '((obj: any, opts: CustomResourceOptions) => void)[]' is not assignable to type '((o: any, opts: CustomResourceOptions) => void)[]'.
    Type '(obj: any, opts: CustomResourceOptions) => void' is not assignable to type '(o: any, opts: CustomResourceOptions) => void'.
      Types of parameters 'opts' and 'opts' are incompatible.
        Type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").CustomResourceOptions' is not assignable to type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").CustomResourceOptions'.
          Types of property 'parent' are incompatible.
            Type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").Resource | undefined' is not assignable to type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").Resource | undefined'.
              Type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").Resource' is not assignable to type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").Resource'.
                Types of property 'getProvider' are incompatible.
                  Type '(moduleMember: string) => import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").ProviderResource | undefined' is not assignable to type '(moduleMember: string) => import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").ProviderResource | undefined'.
                    Type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").ProviderResource | undefined' is not assignable to type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").ProviderResource | undefined'.
                      Type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/kubernetes/node_modules/@pulumi/pulumi/resource").ProviderResource' is not assignable to type 'import("/tmp/p-it-travis-job-helm-9310f60a-973335404/node_modules/@pulumi/pulumi/resource").ProviderResource'.
                        Types have separate declarations of a private property 'pkg'.
  index.ts(63,54): error TS2339: Property 'clusterIP' does not exist on type 'Output<any>'.
    Property 'clusterIP' does not exist on type 'OutputInstance<any>'.
```

I sort of understand what this is getting at (the test lists `@pulumi/pulumi` in it's `package.json` as a dependency, and when we `yarn link` in the version of `@pulumi/kubernetes` we end up with another copy in our `node_modules` folder nested under `@pulumi/kubernetes` because its present in the folder on disk and for some reason these two are not compatible.

I'm a little confused on why Levi's change here fixes it or if it we take the change what would cause it to break again.  I don't think any part of ProviderResource has changed recently, so I don't get why we see these conflicts.  I also don't really understand why this just started to happen.

Do you understand what causes these sorts of problems to manifest?

**Comment by CyrusNajmabadi** [comment]
Yes.  I know what's happening, and it's super annoying.    The basic issue is that (by design) typescript never considers different classes 'compatible' if they have private fields.  So 'ProviderResource' can never be compatible if we ever load multiple versions of pulumi sxs and then do anything that compares 'CustomResourceOptions'.

The fix is easy though.  We just need to not have the 'private' members of this type in the .d.ts.  Then, TS will thnk of these types as compatible.  I can help fix this tomorrow.

**Comment by lblackstone** [comment]
Root issue was fixed. Closing this out.

**Pull request closed without merging**
