### PR TITLE
Add support for k8s 1.20

### LINKED ISSUE #1329: Support k8s 1.20 on release
k8s 1.20 is [scheduled for release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.20) on December 8, 2020. The provider should support 1.20 as soon as it's released.

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)
Fix #1329

### CODE REVIEW

**Comment by lblackstone** [comment]
The official release should be out tomorrow, and I would expect no changes from the current release candidate, so this is RFR

**Review by viveklak — APPROVED** [review]

**Comment by lblackstone** [comment]
No changes in the final release, so merging now.

**Pull request merged**
