### PR TITLE
[helm/v3] Pass provider options to helm invokes

### LINKED ISSUE #1912: `Error: unknown provider ''` when default provider disabled
## Hello!

- Vote on this issue by adding a 👍 reaction
- To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already)

## Issue details

Disabling the default kubernetes provider generates an `Error: unknown provider ''` error with `k8s.helm.v3.Chart`.

pulumi cli version: v3.24.1
pulumi-kubernetes version: v3.16.0

Pulumi.dev.yaml:
```
config:
  pulumi:disable-default-providers:
  - kubernetes
```

index.ts:
```
import * as k8s from '@pulumi/kubernetes'

const k8sProvider = new k8s.Provider(`k8s-provider`, {
  kubeconfig: '/home/ncsibra/.kube/dliver_dev',
})

new k8s.helm.v3.Chart(
  'cert-manager',
  {
    repo: 'jetstack',
    chart: 'cert-manager',
    version: 'v1.5.3',
  },
  {
    provider: k8sProvider,
  }
)
```

pulumi up:
```
     Type                            Name                Plan       Info
 +   pulumi:pulumi:Stack             k8s-cert-manager-dev  create     1 error
 +   ├─ kubernetes:helm.sh/v3:Chart  cert-manager        create
 +   └─ pulumi:providers:kubernetes  k8s-provider        create

Diagnostics:
  pulumi:pulumi:Stack (k8s-cert-manager-dev):
    error: Error: unknown provider ''
        at Object.callback (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@pulumi/runtime/invoke.ts:161:33)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client.ts:338:26)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:426:34)
        at Object.onReceiveStatus (/home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/client-interceptors.ts:389:48)
        at /home/ncsibra/dev/prmrgt-infra/pulumi/node_modules/@grpc/grpc-js/src/call-stream.ts:276:24
        at processTicksAndRejections (node:internal/process/task_queues:78:11)
```

### PR DESCRIPTION
**Pull request by viveklak**
We still need to add support for dotnet and make similar changes for ConfigGroup and ConfigFile as well. I will open a separate issue to track those.

### Related issues (optional)
Fixes #1912

### CODE REVIEW

**Comment by viveklak** [comment]
CC @guineveresaenger who is planning on taking this over.

**Comment by rawkode** [comment]
@viveklak @guineveresaenger can I help get this merged?

**Comment by guineveresaenger** [comment]
Hi! This fell off my radar, and I apologize.

I can take a stab at this tomorrow, but if you think we can merge as-is and that would unblock you @rawcode, that's fine by me.

**Comment by viveklak** [comment]
> Hi! This fell off my radar, and I apologize.
> 
> I can take a stab at this tomorrow, but if you think we can merge as-is and that would unblock you @RawCode, that's fine by me.

I think we can merge as-is for now. We have more work to be done here than just helm chart for Dotnet anyway. We still need to reflect the option to ConfigFile and ConfigGroup as well. I will open a separate ticket to track those once this is merged.

**Review by guineveresaenger — APPROVED** [review]
Thank you for unsticking that test, Vivek!

Let's merge and fix dotnet with the other improvements.

**Pull request merged**
