### PR TITLE
Always merge in OpenAPI spec v1.17

### LINKED ISSUE #927: k8s 1.18 OpenAPI spec removes deprecated API resources
### Problem description

The upcoming 1.18 release removes several API resources that were deprecated and no longer supported as of 1.16. Although they are gone from the OpenAPI spec, we need to continue including them in our SDKs for the sake of users on older versions of k8s. This will require changes in the SDK generators to support.

Affected API resources include:
* `extensions/v1beta1/*`
* `apps/v1beta1/*`
* `apps/v1beta2/*`

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
To maintain support for deprecated API resources in our SDKs, merge
current swagger specs on top of the v1.17.0 spec, which was the last
version containing these definitions.

### Related issues (optional)

Fixes #927

### CODE REVIEW

**Comment by lblackstone** [comment]
I extracted these commits from #872, since the fix isn't directly related to 1.18 support, and I want to include them in other work. Since we are still on k8s 1.17, this is a no-op.

**Comment by pgavlin** [comment]
I'm nervous about this. Can we just merge in the missing elements? I'd prefer to take the current version in any conflicts.

**Comment by lblackstone** [comment]
@pgavlin The merge function is applying the current spec as a patch, so current values should overwrite any old values. Is there a better way I'm not thinking of?

This should be a fairly low-risk change since this only happens when we generate new SDKs, and the results are manually reviewed. It seemed to be working as expected for the 1.18 branch.

**Comment by pgavlin** [comment]
> The merge function is applying the current spec as a patch, so current values should overwrite any old values. Is there a better way I'm not thinking of?

I don't think that's the behavior of the merge. From the docs on https://pkg.go.dev/github.com/RaveNoX/go-jsonmerge?tab=doc:

> For example you have this documents:
> 
> original.json
> 
> ```
> {
>   "number": 1,
>   "string": "value",
>   "object": {
>     "number": 1,
>       "string": "value",
>       "nested object": {
>         "number": 2
>       },
>       "array": [1, 2, 3],
>       "partial_array": [1, 2, 3]
>    }
> }
> ```
> 
> patch.json
> 
> ```
> {
>   "number": 2,
>   "string": "value1",
>   "nonexitent": "woot",
>   "object": {
>     "number": 3,
>     "string": "value2",
>     "nested object": {
>       "number": 4
>     },
>     "array": [3, 2, 1],
>     "partial_array": {
>       "1": 4
>     }
>   }
> }
> ```
> 
> After merge you will have this result:
> 
> ```
> {
>   "number": 2,
>   "string": "value1",
>   "object": {
>     "number": 3,
>     "string": "value2",
>     "nested object": {
>       "number": 4
>     },
>     "array": [3, 2, 1],
>     "partial_array": [1, 4, 3]
>   }
> }
> ```

Note that the contents of `/object/partial_array` include both the old and new values. I don't think that's the behavior we want--I think we want new values to overwrite old values as you described above.

**Comment by lblackstone** [comment]
> I don't think that's the behavior of the merge.

Good catch! I switched to a different merge library, and I think it's working as intended now. Here's the output from the merge example above:

```json
{
  "nonexitent": "woot",
  "number": 2,
  "string": "value2",
  "object": {
    "number": 3,
    "string": "value1",
    "nested object": {
      "number": 4
    },
    "array": [3, 2, 1],
    "partial_array": [1, 2, 3]
  }
}
```

**Comment by pgavlin** [comment]
Can we add some tests to make sure that everything that was in the 1.18+ schema is still in the merged schema?

**Comment by lblackstone** [comment]
> Can we add some tests to make sure that everything that was in the 1.18+ schema is still in the merged schema?

I manually verified this merge with a 3-way diff between 1.17, 1.18-beta.1, and the merged schema. It properly preserved the values that were removed in 1.18, while also overriding values that were changed from 1.17 -> 1.18.

**Pull request merged**
