### PR TITLE
Bump k8s deps

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes
- Bump helm to v3.4.0
- Bump k8s deps to v1.19.2
- Update dependent code as required

### CODE REVIEW

**Comment by lblackstone** [comment]
Looks like this upgrade is causing a new panic. I'll need to investigate further.

```
[ ts/sdk/nodejs/examples/mariadb ]   pulumi:pulumi:Stack (mariadb-p-it-fv-az54-mariadb-c37611a1):
[ ts/sdk/nodejs/examples/mariadb ]     panic: cannot deep copy resource.Computed
[ ts/sdk/nodejs/examples/mariadb ]     goroutine 39 [running]:
[ ts/sdk/nodejs/examples/mariadb ]     k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x277fee0, 0xc0008c2d30, 0xc0005fb2e0, 0xc00166a0c0)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:466 +0x4e6
[ ts/sdk/nodejs/examples/mariadb ]     k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x27145c0, 0xc001643c50, 0xc00163c2b6, 0xa)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:450 +0x157
[ ts/sdk/nodejs/examples/mariadb ]     k8s.io/apimachinery/pkg/runtime.DeepCopyJSONValue(0x27145c0, 0xc001643c20, 0x0, 0x0)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:450 +0x157
[ ts/sdk/nodejs/examples/mariadb ]     k8s.io/apimachinery/pkg/runtime.DeepCopyJSON(...)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/runtime/converter.go:435
[ ts/sdk/nodejs/examples/mariadb ]     k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).DeepCopy(0xc001699778, 0xc001611d40)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/k8s.io/apimachinery@v0.18.8/pkg/apis/meta/v1/unstructured/unstructured.go:146 +0x75
[ ts/sdk/nodejs/examples/mariadb ]     github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.withLastAppliedConfig(0xc001699778, 0xc001699778, 0x2aaeb28, 0xc001643c20)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:2278 +0x65
[ ts/sdk/nodejs/examples/mariadb ]     github.com/pulumi/pulumi-kubernetes/provider/v2/pkg/provider.(*kubeProvider).Create(0xc0008cf2c0, 0x2cd5020, 0xc001643a40, 0xc001646d70, 0xc0008cf2c0, 0x2729c01, 0xc001645080)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/work/pulumi-kubernetes/pulumi-kubernetes/provider/pkg/provider/provider.go:1421 +0x3db
[ ts/sdk/nodejs/examples/mariadb ]     github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler.func1(0x2cd5020, 0xc001643a40, 0x28be160, 0xc001646d70, 0x28ddd20, 0x3e0a8c8, 0x2cd5020, 0xc001643a40)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.11.3-0.20201012185126-156aa9862e15/proto/go/provider.pb.go:2244 +0x89
[ ts/sdk/nodejs/examples/mariadb ]     github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1(0x2cd5020, 0xc001643890, 0x28be160, 0xc001646d70, 0xc00163f2a0, 0xc00163f2c0, 0x0, 0x0, 0x2c7ad20, 0xc000608150)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x2f6
[ ts/sdk/nodejs/examples/mariadb ]     github.com/pulumi/pulumi/sdk/v2/proto/go._ResourceProvider_Create_Handler(0x2951620, 0xc0008cf2c0, 0x2cd5020, 0xc001643890, 0xc001650d20, 0xc00052e880, 0x2cd5020, 0xc001643890, 0xc0016eae00, 0x1be)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v2@v2.11.3-0.20201012185126-156aa9862e15/proto/go/provider.pb.go:2246 +0x150
[ ts/sdk/nodejs/examples/mariadb ]     google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000beea0, 0x2cef9c0, 0xc000001b00, 0xc001648600, 0xc000563ad0, 0x3b85848, 0x0, 0x0, 0x0)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1082 +0x522
[ ts/sdk/nodejs/examples/mariadb ]     google.golang.org/grpc.(*Server).handleStream(0xc0000beea0, 0x2cef9c0, 0xc000001b00, 0xc001648600, 0x0)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:1405 +0xcc5
[ ts/sdk/nodejs/examples/mariadb ]     google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc00054cb30, 0xc0000beea0, 0x2cef9c0, 0xc000001b00, 0xc001648600)
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:746 +0xa5
[ ts/sdk/nodejs/examples/mariadb ]     created by google.golang.org/grpc.(*Server).serveStreams.func1
[ ts/sdk/nodejs/examples/mariadb ]     	/home/runner/go/pkg/mod/google.golang.org/grpc@v1.29.1/server.go:744 +0xa5
[ ts/sdk/nodejs/examples/mariadb ]  
[ ts/sdk/nodejs/examples/mariadb ]   kubernetes:core/v1:Secret (mariadb-app):
[ ts/sdk/nodejs/examples/mariadb ]     error: Preview failed: transport is closing
[ ts/sdk/nodejs/examples/mariadb ]  
[ ts/sdk/nodejs/examples/mariadb ]   kubernetes:core/v1:Service (mariadb-app):
[ ts/sdk/nodejs/examples/mariadb ]     error: transport is closing
```

**Review by justinvp — APPROVED** [review]
LGTM

**Pull request merged**
