### PR TITLE
Respect `namespace` flag in Helm SDK

### PR DESCRIPTION
**Pull request by hausdorff**
This is a first cut at #217, meant to open discussion around tradeoffs of various possible solutions.

The basic issue at is that we expose a `namespace` field in the `helm.v2.Chart` options, which is meant to correspond to `--namespace` flag. `helm template` does not respect this flag, since it does not use Tiller. And, since we depend on `helm template`, this ends up being meaningless to our SDK, too.

There are a few possible options here:

* **Remove the `namespace` flag entirely.** This would be a breaking change and allows us not to deviate from Helm's behavior, while setting the stage to let them fix it for Helm 3, when Tiller is going away. The downside is that we will get this question in perpetuity, probably forever, and some number of users will assume it's actually not the Helm semantics.
* **Set the value of every resource's namespace when `namespace` field is present.** This commit does that. This will solve the issue for ~everyone, since `.metadata.namespace` can be provided to every resource type even if the resource is not namespaced. The downside, is that resources that if we change the namespace of any resources that _aren't_ namespaced, we will inadvertently replace them. Worse, the replacement will fail in some cases, because we cannot create before deleting. Most of the time this won't be a problem, because ~all Helm charts have manually-named resources, but it will cause consternation when it does happen.
* **Allow the provider to make the decision.** This would involve adding a `namespace` field to the args bag that's passed at create/update, and allowing the provider to try to add the namespace if the resource is namespaced. Since the provider has access to the OpenAPI spec, this will probably work in all cases where the namespacing is correctly reported in the OpenAPI spec. Old programs will still work. The downside is that this is considerably more work, and it's not clear whether this is justified by the pain this issue causes. On balance, this is also something that would be useful for the YAML SDK, so it might be worth doing.

Explicitly won't work (without major changes to how the provider works):

* **Trying to be smart about which resources are namespaced.** Detecting which resources are namespaced will have to be implemented and injecting them SDK-side won't work because the Kubernetes provider is the only thing with access to the OpenAPI spec. We could guess for the core types, but this will straight up not work for CRDs.

<hr>

@lblackstone so these are the options as I see them. What do you think?

### CODE REVIEW

**Comment by hausdorff** [comment]
I actually think we probably want option (3). But that would not land for M21.

**Comment by lblackstone** [comment]
Option 3 makes the most sense to me. Option 2 is already possible to do in the user program, so we can suggest that as an option for users in the meantime.

**Comment by hausdorff** [comment]
Since we're going to be solving that anyway, let's close this and bunch the solution in with that.

**Comment by hausdorff** [comment]
("That" being #415.)

**Pull request closed without merging**
