### PR TITLE
#2563: Expose Helm --kube-version argument for contextless diffs

### LINKED ISSUE #2563: Support explicitly passing --kube-version to helm
## Hello!

- Vote on this issue by adding a 👍 reaction
- If you want to implement this feature, comment to let us know (we'll work with you on design, scheduling, etc.)

## Issue details

https://github.com/pulumi/pulumi-kubernetes/issues/753 explained this issue well, but the resolution does not cover one edge case that we cared about. We have a workflow where we would like to run previews without access to the actual K8s API server (just based on pulumi state which IIUC in the case of helm charts should only use helm template). 

https://github.com/pulumi/pulumi-kubernetes/issues/753#issuecomment-875148955 asked for a way to explicitly set `kubeVersion` in the helm args which would have solved our issue as we can explicitly pass this value when running in this semi-offline mode, however the [resolution](https://github.com/pulumi/pulumi-kubernetes/issues/196) to the previous issue was to auto-derive it from the server which doesn't work in our case. Could a `kubeVersion` argument still be added to the helm release / chart options to allow explicit override in these cases?

### Affected area/feature

helm
sdk

### PR DESCRIPTION
**Pull request by henry-fn**
### Proposed changes

This PR exposes the helm template `--kube-version` argument so it can be manually specified in situations when there is no access to the Kubernetes API server (e.g running a diff in CSA mode with no connection to the cluster).

Prior to this merge:
* If there were zero k8s contexts --> this field was unset meaning helm would default to some old version (1.20.0 at the time of writing) if it couldn't connect to the k8s context
* 1+ k8s contexts --> would always try to contact the API server to get the version leading to an error if the API server was unreachable.

This variable will override the behavior in either case, but is mostly useful in the first case or when the context in the second case is malformed / unreachable. 

### Related issues (optional)

Closes #2563

### Notes:

* The files under sdk/* are generated from provider/pkg/gen, please review the files under provider/pkg/gen
* Most changes under provider/pkg/gen seemed straightforward but I did have some trouble with the dotnet code since the tuple in `Unpack.cs` was already at max length. I tried to consolidate the args in a similar style to the rest of the unpack logic but it is likely that this section in particular deserves some extra time whenever someone reviews this code.

### CODE REVIEW

**Comment by henry-fn** [comment]
Any update here? The link seems to show green tests but I don't see that reflected in the build status.

**Review by EronWright — COMMENTED** [review]
The changes in `pkg/gen`, were they done by hand? 
I believe they're generated based on a schema file, but @rquitales will know more about it.

**Comment by hvpeteet** [comment]
Yes I did those by hand because I couldn't find a reference to the helm chart opts in the schema. It is likely I just missed something and would love for this to be generated.

**Comment by rquitales** [comment]
Hello @hvpeteet,

I want to express my appreciation for your work on this PR and your valuable contribution to our project! After an initial review, it appears that the code you've submitted is quite promising, and it's encouraging to see that the test suite is passing.

Regarding the changes in `pkg/gen`, yes, these currently need to be done manually. The Helm Chart resource is currently considered an "overlay" resource, which means that these changes have to be maintained manually in all the languages we support. You can find more details on this in issue #1971.

While I haven't had the chance to build and run this locally to verify its functionality, I would like to suggest the inclusion of some program tests for this feature. If you're able to add tests, we'd be more than happy to provide guidance and assistance to help you create them.

Once again, thank you for your contribution, and we look forward to seeing this enhancement progress and landed. If you have any questions, need assistance with tests, or if there's anything else you'd like to discuss, please feel free to reach out. Your efforts are instrumental in enhancing our project!

**Comment by henry-fn** [comment]
> Hello @hvpeteet,
> 
> I want to express my appreciation for your work on this PR and your valuable contribution to our project! After an initial review, it appears that the code you've submitted is quite promising, and it's encouraging to see that the test suite is passing.
> 
> Regarding the changes in `pkg/gen`, yes, these currently need to be done manually. The Helm Chart resource is currently considered an "overlay" resource, which means that these changes have to be maintained manually in all the languages we support. You can find more details on this in issue #1971.
> 
> While I haven't had the chance to build and run this locally to verify its functionality, I would like to suggest the inclusion of some program tests for this feature. If you're able to add tests, we'd be more than happy to provide guidance and assistance to help you create them.
> 
> Once again, thank you for your contribution, and we look forward to seeing this enhancement progress and landed. If you have any questions, need assistance with tests, or if there's anything else you'd like to discuss, please feel free to reach out. Your efforts are instrumental in enhancing our project!

I will work on some getting some tests added, thanks for confirming that I needed to edit these files by hand.

**Comment by henry-fn** [comment]
@rquitales I added some tests but wasn't able to get the dotnet tests working on my laptop (ARM M2 macbook). Do you think you could take a look at the tests (especially dotnet) when you get a chance? I don't know how much more local dev I can get working easily

**Comment by henry-fn** [comment]
Thanks @rquitales, please let me know if I can do anything else here. IIUC the tests look green 🤞

**Comment by henry-fn** [comment]
@rquitales is anything blocking this from merging?

**Comment by rquitales** [comment]
@henry-fn Apologies for dropping the ball here, this fell into the void of my GitHub notifications. Re-running the tests after rebasing. Will merge and cut a release after this!

**Review by rquitales — APPROVED** [review]

**Pull request merged**
