### PR TITLE
Dependabot Updates combined into one testable PR. 

### PR DESCRIPTION
**Pull request by rshade**
### Proposed changes

Dependabot Updates combined into one testable PR.

### CODE REVIEW

**Comment by rshade** [comment]
I am not sure why this would cause the following dotnet issue? 
```
Diagnostics:
  pulumi:pulumi:Stack (basic_dotnet_kubernetes-p-it-fv-az412-3-basic-621902f1):
    error: update failed

  kubernetes:apiextensions.k8s.io/v1beta1:CustomResourceDefinition (crd):
    warning: apiextensions.k8s.io/v1beta1/CustomResourceDefinition is deprecated by apiextensions.k8s.io/v1/CustomResourceDefinition and not supported by Kubernetes v1.22+ clusters.
    error: resource crontabs.stable.example.com was not successfully created by the Kubernetes API server : customresourcedefinitions.apiextensions.k8s.io "crontabs.stable.example.com" already exists
    ```

**Comment by rshade** [comment]
make test_all throws this:
```
Diagnostics:
  pulumi:pulumi:Stack (crd-tests-p-it-laptop-8f1-step1-e0b22528):
    error: update failed

  kubernetes:apiextensions.k8s.io/v1beta1:CustomResourceDefinition (foobar):
    warning: apiVersion "apiextensions.k8s.io/v1beta1/CustomResourceDefinition" was removed in Kubernetes 1.22. Use "apiextensions.k8s.io/v1/CustomResourceDefinition" instead.
    error: resource foobars.stable.example.com was not successfully created by the Kubernetes API server : apiVersion "apiextensions.k8s.io/v1beta1/CustomResourceDefinition" was removed in Kubernetes 1.22. Use "apiextensions.k8s.io/v1/CustomResourceDefinition" instead.

  kubernetes:stable.example.com/v1:FooBar (my-new-foobar-object):
    error: creation of resource test-namespace-f5656273/my-new-foobar-object failed because the Kubernetes API server reported that the apiVersion for this resource does not exist. Verify that any required CRDs have been created: no matches for kind "FooBar" in version "stable.example.com/v1"```

**Comment by rshade** [comment]
@lblackstone @squaremo Any ideas? Do I need to update those tests? I wouldn't think those libraries would cause these test failures.

**Comment by lblackstone** [comment]
https://cloud.google.com/kubernetes-engine/docs/release-notes#February_10_2023

@squaremo It looks like GKE just removed support for v1.21 clusters, so these tests will need to be updated.

**Review by lblackstone — APPROVED** [review]

**Pull request merged**
