### PR TITLE
Update changelog for 0.20.2

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Comment by lblackstone** [comment]
@hausdorff @metral Any objections to releasing today?

**Comment by lukehoban** [comment]
Let's pull in the changes to adopt latest `@pulumi/pulumi` to carry through the feature highlighted here (for AWS in that case): https://github.com/pulumi/pulumi-aws/commit/2f33c85d16660fa9f3f822b503fc679df36b10d2#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR11.

This is part of https://github.com/pulumi/home/issues/429, but we can take care of it here if we are going to release for other reasons today.

**Comment by lblackstone** [comment]
@lukehoban I won't have time to get to this today, so I'll delay the release until tomorrow, and get that change added in as well.

**Comment by lblackstone** [comment]
Looks like we're already using the new package in the node sdk:
https://github.com/pulumi/pulumi-kubernetes/blob/727c578bb47107f1a4531c3083968e094a44a34e/sdk/nodejs/package.json#L16

Opened #429 for python

**Pull request merged**
