### PR TITLE
Move mocha to devDependencies to prevent downstream errors

### LINKED ISSUE #440: @types/mocha in `dependencies` cause TS errors downstream
Since this particular set of types is not needed to support the runtime (ts or js), it should simply be moved to `devDependencies`.
https://github.com/pulumi/pulumi-kubernetes/blob/master/sdk/nodejs/package.json#L25

TS2403
```
Subsequent variable declarations must have the same type.  Variable 'beforeEach' must be of type 'Lifecycle', but here has type 'HookFunction'.
```

### PR DESCRIPTION
**Pull request by rosskevin**
Closes #440

### CODE REVIEW

**Comment by lblackstone** [comment]
Hi @rosskevin, thanks for the PR! Can you run `make ensure`, commit the changes, and resubmit? Note that you'll need the latest version of `dep` (0.5).

**Comment by rosskevin** [comment]
@lblackstone ran `make ensure` locally, no changes to commit.  It looks like the travis build became non-responsive.

**Comment by lblackstone** [comment]
@rosskevin Sorry about the confusion; looks like Travis flaked on the earlier test I looked at. The current failure is because the `package.json` file is auto-generated from https://github.com/pulumi/pulumi-kubernetes/blob/e4fa04b13a20929c879aca1bbe58fb5a95d16f7c/pkg/gen/nodejs-templates/package.json.mustache

To get this passing, you'll need to update that file to match the changes you made to `package.json`, and then run `make build && make install` to rerun the generator code.

**Comment by lblackstone** [comment]
@rosskevin I'll cut an official release later today, but you should be able to get this change with the  `pulumi/kubernetes: dev` package in about 30 mins. Thanks for the quick turnaround!

**Pull request merged**
