### PR TITLE
Add Java packages overrides to schema

### PR DESCRIPTION
**Pull request by pawelprazak**
### Proposed changes

Fixes https://github.com/pulumi/pulumi-java/issues/381

### Related issues (optional)
Fix https://github.com/pulumi/pulumi-java/issues/381

### CODE REVIEW

**Comment by stack72** [comment]
@pawelprazak is this a breaking change?

**Comment by pawelprazak** [comment]
@stack72 IIUC it should not break things in other languages, but for Java it is very breaking, it will change package names, and also because e.g. eks provider will stop compile until this is released, and only then the changes can be propagated - that is how I understand this dependency between providers

**Review by lblackstone — CHANGES_REQUESTED** [review]
Change LGTM, but need to update the changelog

**Comment by pawelprazak** [comment]
thank you @lblackstone what would you like to see in the CHANGELOG?

**Comment by lblackstone** [comment]
> thank you @lblackstone what would you like to see in the CHANGELOG?

Something [like this](https://github.com/pulumi/pulumi-kubernetes/blob/master/CHANGELOG.md#3190-may-3-2022). Add a note about any breaking change, and then a line linking to the relevant PR. Thanks!

**Comment by pawelprazak** [comment]
updated and rebased

**Review by lblackstone — APPROVED** [review]

**Pull request merged**
