### PR TITLE
Ignore Annotations rather than delete them from the metadata

### PR DESCRIPTION
**Pull request by stack72**
This seems to be a more rounded behaviour

### CODE REVIEW

**Comment by stack72** [comment]
I need to fix that text :/

**Comment by lblackstone** [comment]
@stack72 What's the intended effect of this PR on diffs?

**Comment by stack72** [comment]
So this was something that @pgavlin and I discussed last night - there is no functionality change here removing the metadata felt a bit hammer like so now we just loop over and warn on it

@pgavlin want to give your thoughts on this?

**Comment by stack72** [comment]
I restarted the build as the pulumi stack name already existed

**Comment by pgavlin** [comment]
When preparing these changes, Paul and I discussed the scenarios that might cause this annotation's presence in a user program. We came up with two primary cases:

1. A user has explicitly added this annotation to a resource that was created with Pulumi
2. A user is importing a resource that was previously created with Pulumi

In the first case, the presence of the annotation is probably a mistake, and can cause unintended behavior. Specifically, the k8s provider will _not_ require that an autonamed resource that requires replacement is deleted before its replacement created, and it _will_ generate a new name for the replacement. If the user has hardcoded references to the resource's name, this will invalidate those references and cause the user's deployed infrastructure to misbehave.

In the second case, the presence of the annotation is intentional, as it is required by the engine for the import to succeed. Furthermore, the annotation is _correct_: the original resource was intentionally autonamed, so the aforementioned replacement and naming semantics are expected.

The core challenge with any approach is that the two scenarios above are indistinguishable from the provider's point of view. All the provider can know is that the annotation is present; it can't know _why_ it is present. If we treat the annotation as a bit that can only be set upon creation and can never be removed, we may be able to be more precise with our warnings, as this would allow us to detect the scenario where the user has modified the annotation unintentionally. In that case, we would warn or fail in `Diff` if there is a change to the annotation rather than warning or failing in `Check`.

**Comment by lblackstone** [comment]
Thanks for the detailed explanation, @pgavlin! I think this change is fine to merge as is, and we can open an issue to track the improvements you mention. I suspect this is a fairly minor edge case, so it should be fine to defer that work.

**Review by lblackstone — APPROVED** [review]

**Pull request merged**
