### PR TITLE
Add option to specify that helm chart should do an upgrade

### PR DESCRIPTION
**Pull request by jdmaguire**
### Proposed changes

I'm using an OSS chart that is heavily coupled to whether the chart is doing an install or upgrade. (It relies on the .Release.IsInstall built-in for helm to determine some application logic.)

The [k8s.helm.v3.Chart](https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/provider/invoke_helm_template.go) uses the helm templating golang library but never with the `isUpgrade` configuration. Particularly, this means the chart I'm installing or upgrading always thinks it is being installed. This leads to some interesting bugs. This chart won't change its behaviour since it is so ingrained in how it handles a few operations.

[k8s.helm.v3.Release ](https://github.com/pulumi/pulumi-kubernetes/blob/master/provider/pkg/provider/helm_release.go) does properly set isUpgrade when it is running an upgrade.

Sadly, there's no way to swap from one to another. And sadly, while I can handle downtime, deleting the k8s.helm.v3.Chart resource and adding the k8s.helm.v3.Release resource doesn't work since it tries to do both simultaneously.

**This draft PR proposes an `isUpgrade` flag in the k8s.helm.v3.Chart to get people out of my rare situation where they need to tell the chart that it is doing an upgrade, not an install.** I would prefer if the code itself could figure out if the pulumi k8s.helm.v3.Chart resource exists and sets the upgrade flag as needed, but I can't find a spot in the code where it knows whether it is doing an update or create.

### Related issues (optional)

I asked over in the slack for some help or insight: https://pulumi-community.slack.com/archives/C84L4E3N1/p1671216316161989

If https://github.com/pulumi/pulumi/issues/2877 was implemented, I could seamlessly swap between the k8s.helm.v3.Chart and k8s.helm.v3.Release.

### CODE REVIEW

**Comment by lblackstone** [comment]
Hi @jdmaguire, thanks for the PR! I'm actually working on the Chart implementation this week, and then will be out of office after that for a couple weeks. I'll give this a closer look after that, and keep it in mind during the work this week.

**Comment by jdmaguire** [comment]
Thanks for the information @lblackstone. There's probably nothing I can do, if there is anything I can do to help, shoot me a message here or in the Pulumi slack.

I hope you enjoy your time off next week! 😄 I don't know how your year has been but I'm definitely looking forward to my few weeks off next week.

**Comment by jdmaguire** [comment]
Hi @lblackstone, any updates on the Chart implementation work? I ask because I may bite the bullet and switch to helm.v3.Release (dealing with the pain).

**Comment by lblackstone** [comment]
@jdmaguire Yeah, I made a lot of progress on it into January, but then got pulled off onto another project for the next several months that put this on hold. I expect to wrap this work up later in the year, but I'd recommend trying the helm.Release resource if you need a resolution sooner than that. It's possible to import those resources, so you should be able to drop them from Pulumi state and then swap over to the Release resource without touching the deployed k8s resources. Feel free to reach out in community slack if you need further guidance on that.

**Comment by jdmaguire** [comment]
Thanks for the speedy update Levi. The chart(s) I was having issues with have added a value's flag to override the value for `.Release.IsInstall`/`.Release.IsUpgrade`. I'll rely on them.

Good luck with your long project.

**Pull request closed without merging**
