### PR TITLE
enable configurable Kubernetes API rate limiting via env vars

### LINKED ISSUE #1704: Configurable Kubernetes Client Throttling/Rate Limiting
## Affected area

All Pulumi operations over Kubernetes resources. This would affect the construction of clients from the Kubernetes `client-go` package. 

Based on logs emitted from deploys, it appears that Pulumi may be using a default rate limiting configuration that is too conservative. In particular, it appears `client-go` supports server-side rate limit detection and retries, **and** Pulumi implements its own retry mechanism. 

I tried to follow the `client-go/dynamic` source code to figure out where the rate limiter was specified, but Go is not a language I work with regularly. It does seem like there ought to be, somewhere, a place to swap the [RateLimiter](https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/util/flowcontrol/throttle.go#L28) used. 

I think the `dynamic.NewForConfig` call here: https://github.com/pulumi/pulumi-kubernetes/blob/0072954b2cdf088fc2e336ca4c289929f75ec1a5/provider/pkg/clients/clients.go#L67-L70

Pulumi may be able to supply a "QPS" and "Burst" higher than 5 and 10, respectively: https://github.com/kubernetes/client-go/blob/f6ce18ae578c8cca64d14ab9687824d9e1305a67/rest/config.go#L115-L121

An environment variable would be perfect for us to evaluate the change, such as `PULUMI_KUBE_QPS` and `PULUMI_KUBE_BURST`, but I imagine the Pulumi team has test clusters on major platforms to evaluate for better defaults.

A moderate increase could dramatically reduce deploy times while work is ongoing to reduce the number of API calls necessary by sharing informers / watches on resources a la #1639.

### PR DESCRIPTION
**Pull request by AaronFriel**
### Proposed changes

Adds environment variables `PULUMI_KUBE_CLIENT_QPS` and `PULUMI_KUBE_CLIENT_BURST` to enable tuning Pulumi for large Kubernetes stacks with kube-apiservers that can handle the load.

### Related issues (optional)

Closes #1704

### CODE REVIEW

**Review by lblackstone — CHANGES_REQUESTED** [review]
I think the goal of this change makes sense, but we'd need to plumb the env vars through the [Provider schema](https://github.com/pulumi/pulumi-kubernetes/blob/40a53c9c91e618d6a036306000a01fe7dda75c9f/provider/pkg/gen/schema.go#L37-L221) for consistency. This would allow these values to be set on a per-Provider basis, and also documents the options in the API docs.

While we're making this change, are there any other k8s client settings that would make sense to expose?

**Comment by AaronFriel** [comment]
@lblackstone I'm happy to look at trying to thread the parameters through the provider settings. Go isn't one of my primary languages right now, but I can give it a shot if you think that would be a good MVP. 

I felt like the env var first approach might be good to validate it before shipping it as part of the supported API. what do you think?

**Comment by AaronFriel** [comment]
@lblackstone hey! would you like me to plumb these through the provider schema or OK to use the env vars as an MVP for now? If the former, could you point out a couple key files that I should pay attention to when doing that plumbing?

**Comment by lblackstone** [comment]
@AaronFriel Hey, sorry for the delayed response here. (Have been busy working on the AWS Native provider launch!)

I'm about to make some changes to the provider opts anyway, so I can pull in your changes while I'm at it. I'll tag you on the PR when it's ready.

**Comment by lblackstone** [comment]
Added this feature in https://github.com/pulumi/pulumi-kubernetes/pull/1748, so I'll close this out now. Thanks for the idea and PR!

**Comment by AaronFriel** [comment]
Thank you!

**Pull request closed without merging**
