### PR TITLE
Add more examples

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)
Fix https://github.com/pulumi/pulumi-kubernetes/issues/1765

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
How would we find out if one of those examples wouldn't work anymore? I guess that would require a breaking change - but maybe one could happen at some point, e.g. in our own SDKs? Would it be possible to store the intermediate representation instead and generate the code automatically during the build process, that would also validate them?

**Comment by mikhailshilkov** [comment]
Ah I see https://github.com/pulumi/pulumi-kubernetes/issues/1800 now, makes sense

**Comment by viveklak** [comment]
This should fix https://github.com/pulumi/pulumi-kubernetes/issues/1765?

**Comment by lblackstone** [comment]
Rebased changes

**Review by viveklak — APPROVED** [review]

**Pull request merged**
