### PR TITLE
Upgrade to latest helm dependency

### PR DESCRIPTION
**Pull request by lblackstone**

### CODE REVIEW

**Review by thomas11 — DISMISSED** [review]

**Comment by rquitales** [comment]
Just added a commit to bump k8s to v1.27 for the test cluster. It seems like the client libraries being upgraded here is causing some diffing issues when the test cluster used is `1.24.13-gke.2500`. I haven't done any additional tests to see if it passes on v1.25, or v1.26 either, but GKE v1.27 works. I have also not tested if this is an issue with OSS Kubernetes, or GKE.

**Review by rquitales — APPROVED** [review]

**Comment by rquitales** [comment]
Did more testing, and the test fails on OSS Kubernetes (KinD) and not just GKE.

Tested:
- v1.23.17 (EOL 2023-02-28): FAIL
- v1.24.15 (Latest v1.24.x): FAIL
- v1.24.13: FAIL
- v1.24.1: FAIL
---
- v1.25.11: PASS
- v1.26.6: PASS
- v1.27.3: PASS

Looks like this upgrade is causing a regression for all clusters with v1.24 or lower. @lblackstone What do you think about landing this change?

**Comment by lblackstone** [comment]
> What do you think about landing this change?

Lets hold off for now. This change isn't required at this time, so let's figure out what's causing the regression and we can ideally wait until it's fixed upstream.

**Comment by lblackstone** [comment]
I believe that I identified and fixed the problem causing the test failures. The updated client-go dependency no longer includes dry-run verifier support, and my initial change erroneously changed the support check to use the wrong verifier flag. As a result, the `supportsDryRun` function always returned `false`, so the Diff used inputs rather than the Server-side dry run. There is a known bug with input diffing that fails to detect drift, so the test was failing for this reason.

I updated the dry-run support check to require cluster version of v1.13+ rather than querying the cluster, and verified that the test passes again.

**Comment by lblackstone** [comment]
We decided to move this change to the v4 branch, which already drops support for clusters older than v1.13. I'll rework the PR for that.

**Comment by lblackstone** [comment]
@rquitales Mind giving this another look?

**Review by rquitales — APPROVED** [review]

**Pull request merged**
