### PR TITLE
feat: Add path argument to helm.v3.Release

### LINKED ISSUE #2251: HelmRelease: Path is used as the chart name, triggering unneeded releases
### What happened?

When using a local chart in an HelmRelease, the chart's path is used as the chart's name, and is then stored in the state.

This means that, even if the chart and/or value haven't changed, if you move the chart, it will trigger a new release for nothing. 

I'm working on a tool that is using the automation api and that I'm packaging as a .pex file (a self-extracting and executing python archive). When it's run, it's decompressed in a temporary folder with a random name. The charts are packaged in that archive, which means everything I run the tool, a new release is created, eating a lot of space on the kube cluster (or replacing olders releases with identical ones, depending on the history configuration)

### Steps to reproduce

- Create a local chart, or fetch one from a registry and unpack it
- Create a HelmRelease with this chart (chart="/path/to/chart")
- Run `pulumi up`
- Move the chart, or rename the chart's folder
- Run `pulumi up`

### Expected Behavior

This should be a no-op as no meaningful change was made

### Actual Behavior

- The provider considers the resource has changed (`update [diff: ~chart]`)
- A new helm release is stored on the cluster (as a secret of type `helm.sh/release.v1`)

### Output of `pulumi about`

As I'm using the automation API, I don't have a `Pulumi.yaml` file. I'd love for someone to point me to some doc about how to do that :)

```
CLI          
Version      3.43.1
Go Version   go1.19.1
Go Compiler  gc

Host     
OS       debian
Version  11.5
Arch     x86_64

Pulumi locates its logs in /tmp by default
warning: Failed to read project: no Pulumi.yaml project file found (searching upwards from /home/lta/code/projects/mainstage/main/ops). If you have not created a project yet, use `pulumi new` to do so: no project file found
warning: A new version of Pulumi is available. To upgrade from version '3.43.1' to '3.48.0', visit https://pulumi.com/docs/reference/install/ for manual instructions and release notes.
```

### Additional context

I hope there's an obvious workaround I haven't found (outside of using relative paths which isn't an option ATM)
If not, I'd love some pointers on how to fix this. This isn't really a blocking problem, but it's been annoying me for months, so my annoyance is reaching a sufficiently high level for me to dig into this

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

### PR DESCRIPTION
**Pull request by elthariel**
### Proposed changes

Add a path argument to v3.helm.Release, allowing to ignore_updates on just path which helps handle situation where the path to the chart changes

### Related issues (optional)

Fixes #2251

### CODE REVIEW

**Comment by elthariel** [comment]
Should I commit all the generated code ? Or will it be updated by the CI on release ?

**Comment by kpitzen** [comment]
Hi @elthariel ! Thank you for opening this PR for us - please do commit all the generated code, as that's what eventually gets published with our SDKs. If you could do so in a separate commit so it can be reviewed on its own, that would be much appreciated. Thank you!

**Comment by thomas11** [comment]
Hi @elthariel! If you're still interested, would you resolve the conflict and regenerate? Then we can get this in, if the build is green.

**Comment by elthariel** [comment]
Hey !

I'm still interested. I just haven't had the time recently. But I'll do it when I recover some bandwidth <3

**Comment by mikhailshilkov** [comment]
This PR got stale by now, especially after some changes in v4 release. I'll close it for now - but please open a new PR if you get to it. We appreciate your work, I'm sorry we didn't help you land it!

**Comment by EronWright** [comment]
I believe that the original motivation here is to avoid spurious releases due in the case that the path is volatile. If we solve that issue, this PR might be moot. Please watch https://github.com/pulumi/pulumi-kubernetes/issues/2251 for more updates.

**Pull request closed without merging**
