### PR TITLE
Upgrade to Kubernetes v1.25.0

### PR DESCRIPTION
**Pull request by stack72**

### CODE REVIEW

**Comment by lblackstone** [comment]
It looks like there are a few breaking changes we'll need to look into. We should have until the final release on [August 23](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25) to get this fixed.

**Comment by viveklak** [comment]
Yeah some of the changes look a bit fishy. We do have time here.

**Comment by stack72** [comment]
This is why I wanted to get a WIP open to surface the issues :)

**Comment by lblackstone** [comment]
I took a look at the breaking changes and found the following:

- EndpointHints" missing - This "beta" resource was removed, so no action needed.
- ForZone missing - This "beta" resource was removed, so no action needed.
- missing property "conditions" - This was removed from a "beta" API, so no action needed.
- missing property "timeZone" - This was an "alpha" feature that was removed, so no action needed.
- missing property "lastSuccessfulTime" - This was removed from a "beta" API, so no action needed.
- missing property "hints" - This was removed from a "beta" API, so no action needed.

Since all of these changes affect either alpha or beta APIs, and don't appear to be core features, I don't think we need to do anything special to work around for this release.

**Comment by stack72** [comment]
This is great news @lblackstone - thanks for looking into this :)

**Review by lblackstone — APPROVED** [review]

**Pull request merged**
