### PR TITLE
Updated example with correct syntax

### PR DESCRIPTION
**Pull request by Threpio**
### Proposed changes

Updates to docs to fix Golang example

### CODE REVIEW

**Comment by Threpio** [comment]
I am not sure that the change of the Project CHANGELOG is applicable here?

**Comment by viveklak** [comment]
Thanks for catching this! Could you please follow the contributor guide here: https://github.com/pulumi/pulumi-kubernetes/blob/master/CONTRIBUTING.md? Specifically running the `make build` should update the SDK and docs etc. as well.

**Comment by stack72** [comment]
Hi @Threpio 

Thanks so much for the work here - I have rolled this up (with the requested changes @viveklak  suggested) into #1907 

We really appreciate the work here!

Paul

**Comment by Threpio** [comment]
My apologies for not seeing the comment - I did not get a GitHub notification

**Comment by stack72** [comment]
Not a worry at all @Threpio - I made sure to amend the git commit to ensure your name is part of it :) We really appreciate it!

**Pull request closed without merging**
