### PR TITLE
Fix diff logic for server-side apply mode

### LINKED ISSUE #1667: Secrets are updated not replaced
I updated a `Secret`, and it was `updated` not `replaced`. I am using the server side apply functionality if that helps. This actually triggered a bug for us as we expected the `Deployment` to be updated but wasn't.

_Originally posted by @nesl247 in https://github.com/pulumi/pulumi-kubernetes/issues/1568#issuecomment-892857395_

### PR DESCRIPTION
**Pull request by lblackstone**
### Related issues (optional)
Fix #1667

### CODE REVIEW

**Comment by mikhailshilkov** [comment]
I think I understand the mechanics of the change but missing the bigger picture. Could you give an example of why this is needed and how the merge fixes #1667? Any danger for regression in other diff scenarios that you can identify?

**Review by viveklak — APPROVED** [review]
Looks good. As an aside, we need to put some thought into making the provider a bit more independently testable. I don't think the integration testing framework allows validating diffs for instance.

**Comment by lblackstone** [comment]
> I think I understand the mechanics of the change but I'm missing the bigger picture. Could you give an example of why this is needed and how the merge fixes #1667? Any danger for regression in other diff scenarios that you can identify?

https://github.com/pulumi/pulumi-kubernetes/issues/1667#issuecomment-896302952 has some more details. The server-side diff computes a different patch than the client-side diff, which led to a bug in our replacement computation. By merging those patches (preferring the server-side changes), both of the changes are considered.

The default diff behavior (client-side diff) will not change, and I can't think of a reason why this would break the opt-in server-side diff either.

**Comment by lblackstone** [comment]
> As an aside, we need to put some thought into making the provider a bit more independently testable. I don't think the integration testing framework allows validating diffs for instance.

I agree. It seems like the diff computations are an area that could from some standardization across our native providers.

**Pull request merged**
