### PR TITLE
postpone AdmissionregistrationV1B1 removal

### LINKED ISSUE #1388: admissionregistration.k8s.io/v1beta1 k8s API error when using pulumi and k8s 1.19
### Problem description

I tried to deploy an ECK operator using k8s v1.19 and the following code:
```
import * as k8s from '@pulumi/kubernetes';

const eckOperator = new k8s.yaml.ConfigFile('eck-operator', {
    file: 'https://download.elastic.co/downloads/eck/1.3.0/all-in-one.yaml',
})
```

And got the following error for `pulumi up`:
```
     Type                                                                               Name                                        Plan       Info
 +   pulumi:pulumi:Stack                                                                dataplane_infra-test                        create
 +   ├─ kubernetes:yaml:ConfigFile                                                      eck-operator                                create
 +   │  ├─ kubernetes:core/v1:Namespace                                                 elastic-system                              create
 +   │  ├─ kubernetes:core/v1:Service                                                   elastic-system/elastic-webhook-server       create
 +   │  ├─ kubernetes:core/v1:ServiceAccount                                            elastic-system/elastic-operator             create
 +   │  ├─ kubernetes:core/v1:Secret                                                    elastic-system/elastic-webhook-server-cert  create
 +   │  ├─ kubernetes:core/v1:ConfigMap                                                 elastic-system/elastic-operator             create
 +   │  ├─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                          elastic-operator-view                       create
 +   │  └─ kubernetes:rbac.authorization.k8s.io/v1:ClusterRole                          elastic-operator-edit                       create
     └─ kubernetes:admissionregistration.k8s.io/v1beta1:ValidatingWebhookConfiguration  elastic-webhook.k8s.elastic.co                         1 error

Diagnostics:
  kubernetes:admissionregistration.k8s.io/v1beta1:ValidatingWebhookConfiguration (elastic-webhook.k8s.elastic.co):
    error: apiVersion "admissionregistration.k8s.io/v1beta1/ValidatingWebhookConfiguration" was removed in Kubernetes 1.19. Use "admissionregistration.k8s.io/v1/ValidatingWebhookConfiguration" instead.
    See https://git.k8s.io/kubernetes/CHANGELOG/CHANGELOG-1.19.md#deprecation-1 for more information.
```

This seems like an issue in ECK operator YAML, but `kubectl apply -f https://download.elastic.co/downloads/eck/1.3.0/all-in-one.yaml` works just fine. 
It looks like there's an inconsistency when using pulumi_kubernetes instead of kubectl directly.
As you can see in the k8s issue: [kubernetes/kubernetes#82021 (comment)](https://github.com/kubernetes/kubernetes/issues/82021#issuecomment-636873001), `admissionregistration.k8s.io/v1beta1` removal was planned for 1.19 but was postponed to 1.22.

### Affected product version(s)

Pulumi v2.14.0
@pulumi/kubernetes: 2.7.2
kubernetes: v1.19.3

### PR DESCRIPTION
**Pull request by sunbing81**
### Proposed changes

Per [the comment](https://github.com/kubernetes/kubernetes/issues/82021#issuecomment-636873001), the removal of  `admissionregistration/v1beta1` has been retargeted at 1.22.

### Related issues (optional)

Fixes #1388.

### CODE REVIEW

**Comment by lblackstone** [comment]
@sunbing81 Thanks for the PR! You'll also need to update the related unit test and add a changelog entry to get CI passing.

`    --- FAIL: TestRemovedInVersion/admissionregistration.k8s.io/v1beta1,_Kind=MutatingWebhookConfiguration (0.00s)`

**Review by lblackstone — APPROVED** [review]

**Comment by lblackstone** [comment]
LGTM, thanks for the PR @sunbing81!

**Comment by loopingrage** [comment]
Upgrading to 2.8.2 resolved this for me... for a couple days. Now the error is back. I confirmed that I'm using 2.8.2 as you can see from an `npm ls` command and from doing a `pulumi up --debug`:

Excerpt from pulumi up debug:
```
    pulumi:pulumi:Stack mapped_infrastructure-dev running debug: registering module kubernetes:admissionregistration.k8s.io/v1@2.8.2
    pulumi:pulumi:Stack mapped_infrastructure-dev running debug: registering module kubernetes:admissionregistration.k8s.io/v1beta1@2.8.2
```

I also tried deleting the plugin and reinstalling it:

```
% pulumi plugin rm resource kubernetes           
This will remove 2 plugins from the cache:
    resource kubernetes-2.8.1
    resource kubernetes-2.8.2
Please confirm that this is what you'd like to do by typing ("yes"): yes

% pulumi plugin install resource kubernetes 2.8.2
[resource plugin kubernetes-2.8.2] installing
Downloading plugin: 27.75 MiB / 27.75 MiB [=========================] 100.00% 1s
```

The odd thing is that after running `pulumi up` I see that the 2.8.1 plugin is now installed:
```
kubernetes     resource  2.8.2    70 MB   2 minutes ago   32 seconds ago
kubernetes     resource  2.8.1    70 MB   32 seconds ago  30 seconds ago
```

There is no mention of 2.8.1 in my pulumi debug log though. How do I begin to troubleshoot this?

**Comment by lblackstone** [comment]
> I think I found the issue. I did a `pulumi stack export` and can see that my stack still has references to 2.8.1 which is causing pulumi up to pull in the old version of the provider. What is the recommendation for refreshing my stack with a new provider?

You should be able to export the state file with `pulumi stack export >stack`, replace any instances of `2.8.1` with `2.8.2` in the file, and then `pulumi stack import --file stack`.

**Pull request merged**
