### PR TITLE
Add support for k8s v1.22

### LINKED ISSUE #1550: Support k8s v1.22 on release
k8s 1.22 is [scheduled for release](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.22) on August 4, 2021. The provider should support 1.22 as soon as it's released.

### PR DESCRIPTION
**Pull request by lblackstone**
### Proposed changes

Note: The alpha `EphemeralContainers` kind is [removed in v1.22](https://github.com/kubernetes/kubernetes/pull/101034)

### Related issues (optional)
Fix #1550

### CODE REVIEW

**Comment by stack72** [comment]
@lblackstone very cool that our schema-tools did find the actual breaking change!!

for a break like this, how do we handle it for any users that currently use it? Do we leave it in place and deprecate or just yank it with a changelog entry?

**Comment by lblackstone** [comment]
> for a break like this, how do we handle it for any users that currently use it? Do we leave it in place and deprecate or just yank it with a changelog entry?

In this case, it was for an alpha feature that was just added in 1.21, so I think we'll remove it with a breaking change note.

**Comment by stack72** [comment]
> > for a break like this, how do we handle it for any users that currently use it? Do we leave it in place and deprecate or just yank it with a changelog entry?
> 
> 
> 
> In this case, it was for an alpha feature that was just added in 1.21, so I think we'll remove it with a breaking change note.

Makes sense - anyway, happy to see that we didn't miss this :)

**Comment by lblackstone** [comment]
@viveklak @mikhailshilkov This PR should be ready for the August 4 release date. I've already updated the changelog to note the breaking changes, so you will just need to verify that nothing else has changed when you update the Makefile release to `v1.22.0`.

**Comment by justinvp** [comment]
@mikhailshilkov, @viveklak, before we release a new version of the k8s provider (I assume we'll be doing a release after adopting `v1.22.0`), we'll want #1664 merged, otherwise the version in the Python package will be incorrect.

**Comment by viveklak** [comment]
> @mikhailshilkov, @viveklak, before we release a new version of the k8s provider (I assume we'll be doing a release after adopting `v1.22.0`), we'll want #1664 merged, otherwise the version in the Python package will be incorrect.

Thanks rebased on top of master after merging #1664.

**Review by justinvp — APPROVED** [review]

**Pull request merged**
