### PR TITLE
update helm.ts: add try-catch over helm version

### PR DESCRIPTION
**Pull request by 0x53A**
fixes https://github.com/pulumi/pulumi-kubernetes/issues/1169

I did this change locally in the compiled JS, which fixed my issue.

(I edited it in the github UI bc I was too lazy to clone, let's see if CI likes it)

-------

Feel free to close it if this isn't the correct approach, I'm not too familiar with node

### CODE REVIEW

**Comment by jaxxstorm** [comment]
thanks so much for contributing this! I'll get it tested and early next week

**Comment by leezen** [comment]
FYI I believe this code is generated from a template `/provider/pkg/gen/nodejs-templates/helm/v2/helm.ts` so you'll want to update the template instead of the generated file

**Comment by jaxxstorm** [comment]
Hi @0x53A - i've opened another PR for this here:

https://github.com/pulumi/pulumi-kubernetes/pull/1176

To make sure the tests pass, and fix the merge conflicts. I'll close this out - your contributions will still be included. Thanks so much for this!

**Comment by 0x53A** [comment]
thanks for taking care of it

**Pull request closed without merging**
