### PR TITLE
Enable SourceLink with embedded PDB

### LINKED ISSUE #1196: Enable SourceLink and embed PDB symbols
[SourceLink](https://github.com/dotnet/sourcelink) is essential and would make it easy to step _into_ Pulumi C# source supplied as NuGet packages.

### PR DESCRIPTION
**Pull request by gitfool**
Fixes #1196. Similar to pulumi/pulumi#4967.

### CODE REVIEW

**Comment by gitfool** [comment]
Unrelated build failure:
```
error: PULUMI_ACCESS_TOKEN must be set for login during non-interactive CLI sessions
```

**Comment by lblackstone** [comment]
Thanks for the PR! This change was made as part of our codegen library, so this change will be automatically pulled in by #1253

**Comment by gitfool** [comment]
@lblackstone as with https://github.com/pulumi/pulumi-aws/pull/1037, changes still need to be made upstream so that the [Pulumi.Kubernetes.csproj](https://github.com/pulumi/pulumi-kubernetes/pull/1197/files#diff-8f0483fadfb00eeef88269b43372f430) file is updated / regenerated with the required properties.

**Comment by lblackstone** [comment]
https://github.com/pulumi/pulumi-kubernetes/pull/1253/files?file-filters%5B%5D=#diff-8f0483fadfb00eeef88269b43372f430 is that change, right?

**Comment by gitfool** [comment]
@lblackstone yes, that looks correct. I just need a build and artifacts with that change.

**Comment by gitfool** [comment]
... which I see rolled out just now:

image

LGTM!

**Pull request closed without merging**
